---

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432